set(_CATKIN_CURRENT_PACKAGE "tuto2")
set(tuto2_VERSION "0.0.0")
set(tuto2_MAINTAINER "bassem <bassem@todo.todo>")
set(tuto2_PACKAGE_FORMAT "2")
set(tuto2_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(tuto2_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(tuto2_BUILDTOOL_DEPENDS "catkin")
set(tuto2_BUILDTOOL_EXPORT_DEPENDS )
set(tuto2_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(tuto2_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(tuto2_TEST_DEPENDS )
set(tuto2_DOC_DEPENDS )
set(tuto2_URL_WEBSITE "")
set(tuto2_URL_BUGTRACKER "")
set(tuto2_URL_REPOSITORY "")
set(tuto2_DEPRECATED "")